project_id = "dama-intelligence-workspace"

[api]
enabled = true
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 15

[storage]
enabled = true
file_size_limit = "50MiB"
